sellers = [
    {
        "id": 1,
        "name": "Aria Johnson",
        "seller_type": "artist",
        "logo": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "cover_image": None,
        "bio": "Contemporary digital artist focusing on abstract landscapes.",
        "street_name": "",
        "city": "",
        "postal_code": None,
    },
    {
        "id": 2,
        "name": "Luca Fernández",
        "seller_type": "artist",
        "logo": "https://images.unsplash.com/photo-1758685848406-c737a196f682?q=80&w=1332&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "cover_image": None,
        "bio": "Painter specializing in vibrant urban scenes.",
        "street_name": "",
        "city": "",
        "postal_code": None,
    },
    {
        "id": 3,
        "name": "Nordic Art Gallery",
        "seller_type": "gallery",
        "logo": "https://images.unsplash.com/photo-1633544325196-bcf8bf81ead0?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "cover_image": "https://example.com/covers/nordic.jpg",
        "bio": "A modern gallery showcasing Scandinavian artists.",
        "street_name": "Laugavegur 12",
        "city": "Reykjavik",
        "postal_code": 101,
    },
    {
        "id": 4,
        "name": "Urban Canvas Gallery",
        "seller_type": "gallery",
        "logo": "https://plus.unsplash.com/premium_photo-1669075651685-a9be9fded04b?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "cover_image": "https://example.com/covers/urban.jpg",
        "bio": "Gallery dedicated to street and contemporary art.",
        "street_name": "Main Street 45",
        "city": "Stockholm",
        "postal_code": 11122,
    },
]



artworks = [
    {
        "id": 1,
        "title": "Dreamscape Horizon",
        "medium": "Digital",
        "style": "Abstract",
        "starting_bid_price": 150.00,
        "listing_date": "2024-01-01",
        "width_cm": 60.0,
        "height_cm": 40.0,
        "year_of_creation": 2023,
        "edition": "original",
        "is_sold": False,
        "seller_id": 1,
        "image": "https://images.unsplash.com/photo-1549880338-65ddcdfd017b"
    },
    {
        "id": 2,
        "title": "City Lights",
        "medium": "Oil on Canvas",
        "style": "Urban",
        "starting_bid_price": 300.00,
        "listing_date": "2024-01-02",
        "width_cm": 80.0,
        "height_cm": 60.0,
        "year_of_creation": 2022,
        "edition": "original",
        "is_sold": False,
        "seller_id": 2,
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee"
    },
    {
        "id": 3,
        "title": "Northern Silence",
        "medium": "Acrylic",
        "style": "Minimalism",
        "starting_bid_price": 220.00,
        "listing_date": "2024-01-03",
        "width_cm": 70.0,
        "height_cm": 50.0,
        "year_of_creation": 2021,
        "edition": "limited",
        "is_sold": False,
        "seller_id": 3,
        "image": "https://images.unsplash.com/photo-1492724441997-5dc865305da7"
    },
    {
        "id": 4,
        "title": "Echoes of Nature",
        "medium": "Watercolor",
        "style": "Nature",
        "starting_bid_price": 120.00,
        "listing_date": "2024-01-04",
        "width_cm": 50.0,
        "height_cm": 35.0,
        "year_of_creation": 2020,
        "edition": "open",
        "is_sold": False,
        "seller_id": 3,
        "image": "https://images.unsplash.com/photo-1472214103451-9374bd1c798e"
    },
    {
        "id": 5,
        "title": "Fragments of Time",
        "medium": "Mixed Media",
        "style": "Contemporary",
        "starting_bid_price": 400.00,
        "listing_date": "2024-01-05",
        "width_cm": 90.0,
        "height_cm": 70.0,
        "year_of_creation": 2024,
        "edition": "original",
        "is_sold": False,
        "seller_id": 4,
        "image": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97"
    },
    {
        "id": 6,
        "title": "Silent Geometry",
        "medium": "Ink on Paper",
        "style": "Geometric",
        "starting_bid_price": 180.00,
        "listing_date": "2024-01-06",
        "width_cm": 55.0,
        "height_cm": 45.0,
        "year_of_creation": 2023,
        "edition": "limited",
        "is_sold": True,
        "seller_id": 2,
        "image": "https://images.unsplash.com/photo-1504198453319-5ce911bafcde"
    },
]