# Generated by Django 6.0.4 on 2026-05-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('medium', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('starting_bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_of_creation', models.IntegerField()),
                ('edition', models.CharField(choices=[('original', 'Original Edition'), ('open', 'Open Edition'), ('limited', 'Limited Edition')], max_length=20)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork')),
            ],
        ),
    ]
