# Generated by Django 6.0.4 on 2026-05-11 17:03

from django.db import migrations

def normalize_artworks(apps, schema_editor):
    Artwork = apps.get_model("artworks", "Artwork")
    for artwork in Artwork.objects.all():
        artwork.medium = artwork.medium.strip().capitalize() if artwork.medium else artwork.medium
        artwork.style = artwork.style.strip().capitalize() if artwork.style else artwork.style
        artwork.edition = artwork.edition.strip().lower() if artwork.edition else artwork.edition
        artwork.save()

class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_image_artwork'),
    ]

    operations = [
        migrations.RunPython(normalize_artworks, migrations.RunPython.noop),
    ]
