# Generated by Django 6.0.4 on 2026-05-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_normalize_medium_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
        migrations.AddField(
            model_name='artwork',
            name='mediums',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.medium'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artworks.style'),
        ),
    ]
