# Generated by Django 6.0.4 on 2026-05-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seller_type', models.CharField(
                    choices=[
                        ('artist', 'Artist'),
                        ('gallery', 'Gallery')
                    ],
                    max_length=10
                )),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='seller_cover/')),
                ('bio', models.TextField(blank=True)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]


