<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-05-07 13:43

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 6.0.4 on 2026-05-07 12:04

>>>>>>> 79cead6 (add migrations)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 79cead6 (add migrations)
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
                ('name', models.CharField(max_length=100)),
>>>>>>> 79cead6 (add migrations)
                ('seller_type', models.CharField(choices=[('artist', 'Artist'), ('gallery', 'Gallery')], max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='seller_cover/')),
                ('bio', models.TextField(blank=True)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 79cead6 (add migrations)
            ],
        ),
    ]
