# Generated by Django 6.0.4 on 2026-05-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
    ]
