# Generated by Django 6.0.4 on 2026-05-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_seller_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('gallery', 'Gallery')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='street_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
