# Generated by Django 6.0.4 on 2026-05-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_seller_city_alter_seller_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
