# Generated by Django 6.0.4 on 2026-05-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
