# Generated by Django 6.0.4 on 2026-05-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bid',
            name='unique-amount-per-artwork',
        ),
    ]
