# Generated by Django 6.0.4 on 2026-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_remove_bid_unique_amount_per_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('contingent', 'Contingent')], default='pending', max_length=20),
        ),
    ]
