# Generated by Django 6.0.4 on 2026-05-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='users_accounts',
            new_name='user',
        ),
    ]
